### ISSUE TITLE
Implementation of Network Slimming

### ISSUE THREAD

**Issue by jayroxis** [transmuteAI/ChipNet#7]
Hi,

Is it possible to release the code for your network slimming implementation which is reported in the paper. The original code seems to have problems with large pruning ratio.

Thanks.

**Comment by ubamba98** [comment]
Hi,
You can use the mask-impl from https://github.com/Eric-mingjie/network-slimming  for larger pruning ratio. 

Thanks

**Comment by jayroxis** [comment]
Thank you, we will give it a try.

Regards
